Small tweak to check-aarch64 error message

diff --git a/host-image/usr/bin/check-aarch64 b/host-image/usr/bin/check-aarch64
--- a/host-image/usr/bin/check-aarch64
+++ b/host-image/usr/bin/check-aarch64
@@ -16,10 +16,10 @@ if [[ $(uname -m) != "aarch64" ]]; then
     if ((HAS_ZENITY==1)); then
         zenity --error --no-wrap \
                --title="Error" \
-               --text="Please boot under a 64-bit kernel and try again.\n\n(Add arm_64bit=1 to /boot/config.txt, and restart.)" \
+               --text="Please boot under a 64-bit kernel and try again.\n\n(Ensure arm_64bit=1 set in /boot/config.txt, and restart.)" \
                --timeout=5
     else
-        >&2 echo -e "Error: please boot under a 64-bit kernel and try again.\n\n(Add arm_64bit=1 to /boot/config.txt, and restart.)"
+        >&2 echo -e "Error: please boot under a 64-bit kernel and try again.\n\n(Ensure arm_64bit=1 set in /boot/config.txt, and restart.)"
     fi
     exit 1
 fi
