Modify ds-64- scripts so they work in absence of zenity
For use in CLI-only host systems

diff --git a/host-image/usr/bin/ds64-runner b/host-image/usr/bin/ds64-runner
--- a/host-image/usr/bin/ds64-runner
+++ b/host-image/usr/bin/ds64-runner
@@ -15,26 +15,37 @@ DS64_CONF="/etc/ds64.conf"
 [[ -s "${DS64_CONF}" ]] && source "${DS64_CONF}"
 DS64_NAME="${DS64_NAME:-debian-buster-64}"
 DS64_DIR="${DS64_DIR:-/var/lib/machines/${DS64_NAME}}"
+HAS_ZENITY=0
+which zenity &>/dev/null && [[ ${DISPLAY:-} ]] && HAS_ZENITY=1
 
 if ! ds64-running; then
-        zenity --error --no-wrap \
-  --title="Error starting 64-bit program" \
-  --text="The ${DS64_NAME} container is not running!\nPlease start it and try again." \
-  --timeout=5
-        exit 1
+    if ((HAS_ZENITY==1)); then
+	zenity --error --no-wrap \
+	       --title="Error starting 64-bit program" \
+	       --text="The ${DS64_NAME} container is not running!\nPlease start it and try again." \
+	       --timeout=5
+    else
+	>&2 echo -e "Error starting 64-bit program: the ${DS64_NAME} container is not running!\nPlease start it and try again."
+    fi
+    exit 1
 fi
 # have we already been given the program to run via
 # the command line?
 if (($#==0)); then
-	# no, must ask the user
+    # no, must ask the user if we can do so elegantly, error out otherwise
+    if ((HAS_ZENITY==1)); then
 	if ! P=$(zenity --entry --title="Run 64-bit program" \
-  --width=400 \
-  --text="Please enter the 64-bit program to run\n(parameters allowed):"); then
+			--width=400 \
+			--text="Please enter the 64-bit program to run\n(parameters allowed):"); then
 		exit 1
 	fi
 	# force it through a "which" lookup, this will work for full paths
 	# and names; parse into array to allow arguments
 	read -ra PA <<< "${P}"
+    else
+	>&2 echo "Error: you must pass a command to execute (parameters allowed)."
+	exit 1
+    fi
 else
 	# yes, just slurp it
 	PA=("${@}")
diff --git a/host-image/usr/bin/ds64-shell b/host-image/usr/bin/ds64-shell
--- a/host-image/usr/bin/ds64-shell
+++ b/host-image/usr/bin/ds64-shell
@@ -10,27 +10,33 @@ DS64_CONF="/etc/ds64.conf"
 DS64_NAME="${DS64_NAME:-debian-buster-64}"
 DS64_DIR="${DS64_DIR:-/var/lib/machines/${DS64_NAME}}"
 GUEST_LIBGL_ALWAYS_SOFTWARE="${GUEST_LIBGL_ALWAYS_SOFTWARE:-1}"
+HAS_ZENITY=0
+which zenity &>/dev/null && [[ ${DISPLAY:-} ]] && HAS_ZENITY=1
 
 if ! ds64-running; then
+    if ((HAS_ZENITY==1)); then
         zenity --error --no-wrap \
-  --title="Error starting 64-bit shell" \
-  --text="The ${DS64_NAME} container is not running!\nPlease start it and try again." \
-  --timeout=5
-        exit 1
+	       --title="Error starting 64-bit shell" \
+	       --text="The ${DS64_NAME} container is not running!\nPlease start it and try again." \
+	       --timeout=5
+    else
+	>&2 echo -e "Error starting 64-bit shell: the ${DS64_NAME} container is not running!\nPlease start it and try again."
+    fi
+    exit 1
 fi
 U="$(id --user)"
 exec sudo machinectl shell \
-	--setenv=QT_AUTO_SCREEN_SCALE_FACTOR=0 \
-	--setenv=DISPLAY="${DISPLAY}" \
-	--setenv=XAUTHORITY="${XAUTHORITY}-allhosts" \
-	--setenv=LIBGL_ALWAYS_SOFTWARE="${GUEST_LIBGL_ALWAYS_SOFTWARE}" \
-	--setenv=USER="${USER}" \
-	--setenv=LANG="${LANG}" \
-	--setenv=NO_AT_BRIDGE="${NO_AT_BRIDGE}" \
-	--setenv=DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${U}/bus" \
-	--setenv=PULSE_SERVER="unix:/run/host-user/${U}/pulse/native" \
-	--setenv=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games" \
-	--uid=${U} \
-	"${DS64_NAME}" \
-	/bin/bash \
-	"${@}"
+     --setenv=QT_AUTO_SCREEN_SCALE_FACTOR=0 \
+     --setenv=DISPLAY="${DISPLAY}" \
+     --setenv=XAUTHORITY="${XAUTHORITY}-allhosts" \
+     --setenv=LIBGL_ALWAYS_SOFTWARE="${GUEST_LIBGL_ALWAYS_SOFTWARE}" \
+     --setenv=USER="${USER}" \
+     --setenv=LANG="${LANG}" \
+     --setenv=NO_AT_BRIDGE="${NO_AT_BRIDGE}" \
+     --setenv=DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${U}/bus" \
+     --setenv=PULSE_SERVER="unix:/run/host-user/${U}/pulse/native" \
+     --setenv=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games" \
+     --uid=${U} \
+     "${DS64_NAME}" \
+     /bin/bash \
+     "${@}"
diff --git a/host-image/usr/bin/ds64-stop b/host-image/usr/bin/ds64-stop
--- a/host-image/usr/bin/ds64-stop
+++ b/host-image/usr/bin/ds64-stop
@@ -9,34 +9,48 @@ DS64_CONF="/etc/ds64.conf"
 [[ -s "${DS64_CONF}" ]] && source "${DS64_CONF}"
 DS64_NAME="${DS64_NAME:-debian-buster-64}"
 DS64_DIR="${DS64_DIR:-/var/lib/machines/${DS64_NAME}}"
+HAS_ZENITY=0
+which zenity &>/dev/null && [[ ${DISPLAY:-} ]] && HAS_ZENITY=1
 
 if ! ds64-running; then
+    if ((HAS_ZENITY==1)); then
         zenity --info --no-wrap \
-  --title="Nothing to do" \
-  --text="The ${DS64_NAME} container is already stopped." \
-  --timeout=5
-        exit 0
+               --title="Nothing to do" \
+               --text="The ${DS64_NAME} container is already stopped." \
+               --timeout=5
+    else
+        >&2 echo "Nothing to do: the ${DS64_NAME} container is already stopped."
+    fi
+    exit 0
 fi
 sudo machinectl stop "${DS64_NAME}"
 RUNNING=1
 for ((i=0;i<10;i++)); do
-        if ! ds64-running; then
-                RUNNING=0
-                break
-        fi
-	sleep 1
+    if ! ds64-running; then
+        RUNNING=0
+        break
+    fi
+    sleep 1
 done
 if ((RUNNING==0)); then
+    if ((HAS_ZENITY==1)); then
         zenity --info --no-wrap \
-  --title="Success" \
-  --text="The ${DS64_NAME} container is now stopped." \
-  --timeout=5
-        exit 0
+               --title="Success" \
+               --text="The ${DS64_NAME} container is now stopped." \
+               --timeout=5
+    else
+        echo "Success: the ${DS64_NAME} container is now stopped."
+    fi
+    exit 0
 else
-	zenity --error --no-wrap \
-  --title="Error" \
-  --text="Failed to stop the ${DS64_NAME} container!" \
-  --timeout=5
-        exit 1
+    if ((HAS_ZENITY==1)); then
+        zenity --error --no-wrap \
+               --title="Error" \
+               --text="Failed to stop the ${DS64_NAME} container!" \
+               --timeout=5
+    else
+        >&2 echo "Error: failed to stop the ${DS64_NAME} container!"
+    fi
+    exit 1
 fi
 
